### ISSUE TITLE
[Question] Should the `StateController.kt` be renamed?

### ISSUE THREAD

**Issue by madhead** [meetacy/ksm#3]
… to `StateContext.kt` or something else? It doesn't have a single mention and doesn't seem to deal with the the `StateController`? Then, why does it have such a name?

https://github.com/meetacy/ksm/blob/main/core/src/commonMain/kotlin/ksm/plugin/StateController.kt

**Comment by y9san9** [comment]
There is no such file right now, I assume I reworked it
